name: Build Ubiety.Logging.Core

on: [push]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Install GitVersion
        uses: gittools/actions/setup-gitversion@v0.3.1
        with:
          versionSpec: "5.1.x"
      - uses: actions/checkout@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Fetch tags for GitVersion
        run: |
          git fetch --tags
          git branch --create-reflog ${{steps.extract_branch.outputs.branch}} origin/${{steps.extract_branch.outputs.branch}}
      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/execute-gitversion@v0.3.1
      - name: Build
        run: ./build.sh
